var webpack = require('webpack')
var config = require('./webpack.config.js')
var BundleTracker = require('webpack-bundle-tracker');

config.output.path = require('path').resolve('./assets/dist/') // This is where the prod JS file goes after it is generated. collectstatic will copy it over to STATIC_ROOT
//config.output.publicPath= '/static/dist/' // This will override the url generated by django's staticfiles. This done because we are building the prod webpack locally rather than on prod
config.output.publicPath= 'https://d1c1zft1fr6c2j.cloudfront.net/dist/' // This will override the url generated by django's staticfiles. This done because we are building the prod webpack locally rather than on prod

config.plugins = [
  new BundleTracker({filename: './webpack-stats-prod.json'}),

  // removes a lot of debugging code in React
  new webpack.DefinePlugin({
    'process.env': {
      'NODE_ENV': JSON.stringify('production')
  }}),

  // keeps hashes consistent between compilations
  new webpack.optimize.OccurenceOrderPlugin(),

  // minifies your code
  new webpack.optimize.UglifyJsPlugin({
    compressor: {
      warnings: false
    }
  })
]

config.entry = ['./assets/js/index']

module.exports = config;
